version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./backend:/app
    working_dir: /app
    command: sh -c "python create_test_data.py && python main.py"
    
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
      
  test:
    build: ./backend
    volumes:
      - .:/workspace
    working_dir: /workspace
    depends_on:
      - backend
      - frontend
    command: sh -c "sleep 30 && ./test_api.sh && ./test_user_stories.sh"
    profiles:
      - test
